version: "3"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: always
    depends_on:
      - php

  php:
    image: php:7-fpm-alpine
    volumes:
      - ./src:/var/www/html
    restart: always
    user: 1000:1000
